### ISSUE TITLE
Try not to use `cl_dict`

### ISSUE THREAD

**Issue by tseaver** [zopefoundation/zope.proxy#2]
In https://bugs.launchpad.net/zope.proxy/+bug/958117, @therve reported:

> It'd be nice to not use this implementation detail, to hope to be able to compile under pypy one day. Here's a proposed patch:

``` patch
=== modified file 'zope/proxy/_zope_proxy_proxy.c'
--- zope/proxy/_zope_proxy_proxy.c 2012-02-23 14:05:31 +0000
+++ zope/proxy/_zope_proxy_proxy.c 2012-03-17 19:46:22 +0000
@@ -174,13 +174,15 @@

         if (((PyTypeObject *)base) != &ProxyType) {
             if (PyClass_Check(base))
- dict = ((PyClassObject *)base)->cl_dict;
+ dict = GetAttrString(base, "__dict__");
             else {
                 assert(PyType_Check(base));
                 dict = ((PyTypeObject *)base)->tp_dict;
+ Py_INCREF(dict);
             }
             assert(dict && PyDict_Check(dict));
             res = PyDict_GetItem(dict, name);
+ Py_DECREF(dict);
             if (res != NULL)
                 return res;
         }
```

> Thanks!

**Comment by tseaver** [comment]
I tried porting the patch to the current trunk in f66e57b, but it breaks doctest snippets:

```python
**********************************************************************
File "narr.rst", line 28, in default
Failed example:
    p.x = 'x'
Exception raised:
    Traceback (most recent call last):
      File "/opt/Python-2.6.9/lib/python2.6/doctest.py", line 1253, in __run
        compileflags, 1) in test.globs
      File "<doctest default[0]>", line 1, in <module>
        p.x = 'x'
      File "/home/tseaver/projects/Zope/Z3/zope.proxy/.tox/docs/lib/python2.6/site-packages/zope/proxy/__init__.py", line 121, in __setattr__
        return setattr(self._wrapped, name, value)
    AttributeError: 'list' object has no attribute 'x'
**********************************************************************
File "narr.rst", line 29, in default
Failed example:
    p.x
Exception raised:
    Traceback (most recent call last):
      File "/opt/Python-2.6.9/lib/python2.6/doctest.py", line 1253, in __run
        compileflags, 1) in test.globs
      File "<doctest default[1]>", line 1, in <module>
        p.x
      File "/home/tseaver/projects/Zope/Z3/zope.proxy/.tox/docs/lib/python2.6/site-packages/zope/proxy/__init__.py", line 113, in __getattr__
        return getattr(self._wrapped, name)
    AttributeError: 'list' object has no attribute 'x'
**********************************************************************
File "narr.rst", line 31, in default
Failed example:
    p.f()
Exception raised:
    Traceback (most recent call last):
      File "/opt/Python-2.6.9/lib/python2.6/doctest.py", line 1253, in __run
        compileflags, 1) in test.globs
      File "<doctest default[2]>", line 1, in <module>
        p.f()
      File "<doctest default[1]>", line 5, in f
      File "/home/tseaver/projects/Zope/Z3/zope.proxy/.tox/docs/lib/python2.6/site-packages/zope/proxy/__init__.py", line 113, in __getattr__
        return getattr(self._wrapped, name)
    AttributeError: 'list' object has no attribute 'x'
**********************************************************************
File "narr.rst", line 76, in default
Failed example:
    p.z = 1
Exception raised:
    Traceback (most recent call last):
      File "/opt/Python-2.6.9/lib/python2.6/doctest.py", line 1253, in __run
        compileflags, 1) in test.globs
      File "<doctest default[8]>", line 1, in <module>
        p.z = 1
      File "/home/tseaver/projects/Zope/Z3/zope.proxy/.tox/docs/lib/python2.6/site-packages/zope/proxy/__init__.py", line 123, in __setattr__
        return object.__setattr__(self, name, value)
    AttributeError: 'MyProxy' object attribute 'z' is read-only
**********************************************************************
File "narr.rst", line 77, in default
Failed example:
    o.z, p.z
Exception raised:
    Traceback (most recent call last):
      File "/opt/Python-2.6.9/lib/python2.6/doctest.py", line 1253, in __run
        compileflags, 1) in test.globs
      File "<doctest default[9]>", line 1, in <module>
        o.z, p.z
    AttributeError: MyOb instance has no attribute 'z'
**********************************************************************
```

**Comment by jamadden** [comment]
Since there's a pure-python implementation now that does run on PyPy, is this still relevant?

**Comment by icemac** [comment]
This issue has been inactive for years now. Closing it therefore.
