### ISSUE TITLE
zope.proxy 4.5.0 broken on Python 2.7

### ISSUE THREAD

**Issue by cjwatson** [zopefoundation/zope.proxy#49]
### What I did:

```
git clone https://git.launchpad.net/lazr.restful
cd lazr.restful
# ensure python2.7 is available on $PATH by whatever means you prefer (e.g. pyenv)
tox -r -e py27
```

### What I expect to happen:

Tests pass; I've confirmed that they passed with zope.proxy 4.4.0.

### What actually happened:

```
py27 run-test: commands[0] | zope-testrunner --test-path src --tests-pattern '^tests'
Running zope.testrunner.layer.UnitTests tests:
  Set up zope.testrunner.layer.UnitTests in 0.000 seconds.


Failure in test /home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/lazr/restful/docs/checker-utilities.rst
Failed doctest test for checker-utilities.rst
  File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/lazr/restful/docs/checker-utilities.rst", line 0

----------------------------------------------------------------------
File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/lazr/restful/docs/checker-utilities.rst", line 49, in checker-utilities.rst
Failed example:
    print(debug_proxy(ProxyFactory(content)))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest checker-utilities.rst[9]>", line 1, in <module>
        print(debug_proxy(ProxyFactory(content)))
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/lazr/restful/debug.py", line 73, in debug_proxy
        for proxy in zope.proxy.ProxyIterator(obj):
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/zope/proxy/__init__.py", line 30, in ProxyIterator
        p = getProxiedObject(p)
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/zope/proxy/__init__.py", line 476, in py_getProxiedObject
        return obj._wrapped
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/zope/security/proxy.py", line 153, in __getattr__
        checker.check_getattr(wrapped, name)
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/zope/security/checker.py", line 269, in check
        raise ForbiddenAttribute(name, object)
       - class: __builtin__.MyContent
       - type: __builtin__.MyContent
    ForbiddenAttribute: ('_wrapped', <MyContent object at 0x7fd29997a290>)
----------------------------------------------------------------------
File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/lazr/restful/docs/checker-utilities.rst", line 58, in checker-utilities.rst
Failed example:
    print(debug_proxy(ProxyFactory(content)))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest checker-utilities.rst[12]>", line 1, in <module>
        print(debug_proxy(ProxyFactory(content)))
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/lazr/restful/debug.py", line 73, in debug_proxy
        for proxy in zope.proxy.ProxyIterator(obj):
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/zope/proxy/__init__.py", line 30, in ProxyIterator
        p = getProxiedObject(p)
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/zope/proxy/__init__.py", line 476, in py_getProxiedObject
        return obj._wrapped
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/zope/security/proxy.py", line 153, in __getattr__
        checker.check_getattr(wrapped, name)
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/zope/security/checker.py", line 269, in check
        raise ForbiddenAttribute(name, object)
       - class: __builtin__.MyContent
       - type: __builtin__.MyContent
    ForbiddenAttribute: ('_wrapped', <MyContent object at 0x7fd29997a290>)
----------------------------------------------------------------------
File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/lazr/restful/docs/checker-utilities.rst", line 67, in checker-utilities.rst
Failed example:
    print(debug_proxy(ProxyFactory(content)))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest checker-utilities.rst[15]>", line 1, in <module>
        print(debug_proxy(ProxyFactory(content)))
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/lazr/restful/debug.py", line 73, in debug_proxy
        for proxy in zope.proxy.ProxyIterator(obj):
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/zope/proxy/__init__.py", line 30, in ProxyIterator
        p = getProxiedObject(p)
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/zope/proxy/__init__.py", line 476, in py_getProxiedObject
        return obj._wrapped
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/zope/security/proxy.py", line 153, in __getattr__
        checker.check_getattr(wrapped, name)
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/zope/security/checker.py", line 269, in check
        raise ForbiddenAttribute(name, object)
       - class: __builtin__.MyContent
       - type: __builtin__.MyContent
    ForbiddenAttribute: ('_wrapped', <MyContent object at 0x7fd29997a290>)



Failure in test /home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/lazr/restful/docs/debug.rst
Failed doctest test for debug.rst
  File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/lazr/restful/docs/debug.rst", line 0

----------------------------------------------------------------------
File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/lazr/restful/docs/debug.rst", line 25, in debug.rst
Failed example:
    print(debug_proxy(ProxyBase(1)))
Differences (ndiff with -expected +actual):
    - zope.proxy.ProxyBase
    + zope.proxy.PyProxyBase
    ?             ++
    + <BLANKLINE>
----------------------------------------------------------------------
File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/lazr/restful/docs/debug.rst", line 34, in debug.rst
Failed example:
    print(debug_proxy(SimpleProxy(ProxyBase(1))))
Differences (ndiff with -expected +actual):
      SimpleProxy
    - zope.proxy.ProxyBase
    + zope.proxy.PyProxyBase
    ?             ++
    + <BLANKLINE>
----------------------------------------------------------------------
File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/lazr/restful/docs/debug.rst", line 48, in debug.rst
Failed example:
    print(debug_proxy(p))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest debug.rst[9]>", line 1, in <module>
        print(debug_proxy(p))
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/lazr/restful/debug.py", line 73, in debug_proxy
        for proxy in zope.proxy.ProxyIterator(obj):
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/zope/proxy/__init__.py", line 30, in ProxyIterator
        p = getProxiedObject(p)
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/zope/proxy/__init__.py", line 476, in py_getProxiedObject
        return obj._wrapped
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/zope/security/proxy.py", line 153, in __getattr__
        checker.check_getattr(wrapped, name)
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/zope/security/checker.py", line 269, in check
        raise ForbiddenAttribute(name, object)
       - class: __builtin__.int
       - type: __builtin__.int
    ForbiddenAttribute: ('_wrapped', 1)



Failure in test /home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/lazr/restful/docs/webservice-declarations.rst
Failed doctest test for webservice-declarations.rst
  File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/lazr/restful/docs/webservice-declarations.rst", line 0

----------------------------------------------------------------------
File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/lazr/restful/docs/webservice-declarations.rst", line 2740, in webservice-declarations.rst
Failed example:
    print(debug_proxy(ProxyFactory(entry_adapter)))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest webservice-declarations.rst[462]>", line 1, in <module>
        print(debug_proxy(ProxyFactory(entry_adapter)))
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/lazr/restful/debug.py", line 73, in debug_proxy
        for proxy in zope.proxy.ProxyIterator(obj):
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/zope/proxy/__init__.py", line 30, in ProxyIterator
        p = getProxiedObject(p)
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/zope/proxy/__init__.py", line 476, in py_getProxiedObject
        return obj._wrapped
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/zope/security/proxy.py", line 153, in __getattr__
        checker.check_getattr(wrapped, name)
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/zope/security/checker.py", line 269, in check
        raise ForbiddenAttribute(name, object)
       - class: lazr.restful.declarations.BookEntry_betaAdapter
       - type: lazr.restful.declarations.BookEntry_betaAdapter
    ForbiddenAttribute: ('_wrapped', <lazr.restful.declarations.BookEntry_betaAdapter object at 0x7fd299866390>)
----------------------------------------------------------------------
File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/lazr/restful/docs/webservice-declarations.rst", line 2745, in webservice-declarations.rst
Failed example:
    print(debug_proxy(ProxyFactory(collection_adapter)))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest webservice-declarations.rst[463]>", line 1, in <module>
        print(debug_proxy(ProxyFactory(collection_adapter)))
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/lazr/restful/debug.py", line 73, in debug_proxy
        for proxy in zope.proxy.ProxyIterator(obj):
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/zope/proxy/__init__.py", line 30, in ProxyIterator
        p = getProxiedObject(p)
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/zope/proxy/__init__.py", line 476, in py_getProxiedObject
        return obj._wrapped
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/zope/security/proxy.py", line 153, in __getattr__
        checker.check_getattr(wrapped, name)
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/zope/security/checker.py", line 269, in check
        raise ForbiddenAttribute(name, object)
       - class: lazr.restful.declarations.BookSetCollectionAdapter___Earliest
       - type: lazr.restful.declarations.BookSetCollectionAdapter___Earliest
    ForbiddenAttribute: ('_wrapped', <lazr.restful.declarations.BookSetCollectionAdapter___Earliest object at 0x7fd2999b9a90>)
----------------------------------------------------------------------
File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/lazr/restful/docs/webservice-declarations.rst", line 2749, in webservice-declarations.rst
Failed example:
    print(debug_proxy(ProxyFactory(read_method_adapter)))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest webservice-declarations.rst[464]>", line 1, in <module>
        print(debug_proxy(ProxyFactory(read_method_adapter)))
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/lazr/restful/debug.py", line 73, in debug_proxy
        for proxy in zope.proxy.ProxyIterator(obj):
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/zope/proxy/__init__.py", line 30, in ProxyIterator
        p = getProxiedObject(p)
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/zope/proxy/__init__.py", line 476, in py_getProxiedObject
        return obj._wrapped
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/zope/security/proxy.py", line 153, in __getattr__
        checker.check_getattr(wrapped, name)
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/zope/security/checker.py", line 269, in check
        raise ForbiddenAttribute(name, object)
       - class: lazr.restful.declarations.GET_ICachedBookSet_getAllBooks_beta
       - type: lazr.restful.declarations.GET_ICachedBookSet_getAllBooks_beta
    ForbiddenAttribute: ('_wrapped', <lazr.restful.declarations.GET_ICachedBookSet_getAllBooks_beta object at 0x7fd29993dc50>)
----------------------------------------------------------------------
File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/lazr/restful/docs/webservice-declarations.rst", line 2753, in webservice-declarations.rst
Failed example:
    print(debug_proxy(ProxyFactory(write_method_adapter)))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest webservice-declarations.rst[465]>", line 1, in <module>
        print(debug_proxy(ProxyFactory(write_method_adapter)))
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/lazr/restful/debug.py", line 73, in debug_proxy
        for proxy in zope.proxy.ProxyIterator(obj):
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/zope/proxy/__init__.py", line 30, in ProxyIterator
        p = getProxiedObject(p)
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/zope/proxy/__init__.py", line 476, in py_getProxiedObject
        return obj._wrapped
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/zope/security/proxy.py", line 153, in __getattr__
        checker.check_getattr(wrapped, name)
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/zope/security/checker.py", line 269, in check
        raise ForbiddenAttribute(name, object)
       - class: lazr.restful.declarations.POST_IBookOnSteroids_checkout_beta
       - type: lazr.restful.declarations.POST_IBookOnSteroids_checkout_beta
    ForbiddenAttribute: ('_wrapped', <lazr.restful.declarations.POST_IBookOnSteroids_checkout_beta object at 0x7fd29986d250>)
----------------------------------------------------------------------
File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/lazr/restful/docs/webservice-declarations.rst", line 2757, in webservice-declarations.rst
Failed example:
    print(debug_proxy(ProxyFactory(factory_method_adapter)))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest webservice-declarations.rst[466]>", line 1, in <module>
        print(debug_proxy(ProxyFactory(factory_method_adapter)))
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/lazr/restful/debug.py", line 73, in debug_proxy
        for proxy in zope.proxy.ProxyIterator(obj):
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/zope/proxy/__init__.py", line 30, in ProxyIterator
        p = getProxiedObject(p)
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/zope/proxy/__init__.py", line 476, in py_getProxiedObject
        return obj._wrapped
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/zope/security/proxy.py", line 153, in __getattr__
        checker.check_getattr(wrapped, name)
      File "/home/cjwatson/src/canonical/lazr.restful/lazr.restful/.tox/py27/lib/python2.7/site-packages/zope/security/checker.py", line 269, in check
        raise ForbiddenAttribute(name, object)
       - class: lazr.restful.declarations.POST_IBookSetOnSteroids_create_book_beta
       - type: lazr.restful.declarations.POST_IBookSetOnSteroids_create_book_beta
    ForbiddenAttribute: ('_wrapped', <lazr.restful.declarations.POST_IBookSetOnSteroids_create_book_beta object at 0x7fd29986d490>)

  Ran 163 tests with 3 failures, 0 errors and 0 skipped in 4.562 seconds.
```

Of course it's possible that this is a bug in our code; but since zope.proxy 4.5.0 doesn't seem to have introduced any intentional changes other than metadata, and since it was only released today, it seems at least possible that the Python 2.7 wheel is broken in some way, so I thought I'd file this as soon as possible.

Tests for other Python versions work fine.

### What version of Python and Zope/Addons I am using:

Ubuntu 20.04, Python 2.7.18 (for this particular test), zope.proxy 4.5.0, zope.interface 5.4.0, zope.security 5.1.1.

**Comment by cjwatson** [comment]
Here's a reduced test case that exits with no output when using zope.proxy 4.4.0 on Python 2.7.18, but raises `ForbiddenAttribute` when using zope.proxy 4.5.0:

```python
from zope.interface import Interface, implementer
from zope.proxy import ProxyIterator
from zope.security.checker import Checker, ProxyFactory, defineChecker


class MySchema(Interface):
    pass


@implementer(MySchema)
class MyContent(object):
    pass


defineChecker(MyContent, Checker({}, {}))
list(ProxyIterator(ProxyFactory(MyContent())))
```

**Comment by icemac** [comment]
Works on my machine:

```
$ git clone https://git.launchpad.net/lazr.restful
Klone nach 'lazr.restful'...
remote: Enumerating objects: 9561, done.
remote: Counting objects: 100% (9561/9561), done.
remote: Compressing objects: 100% (2224/2224), done.
remote: Total 9561 (delta 6676), reused 8988 (delta 6215)
Empfange Objekte: 100% (9561/9561), 13.79 MiB | 2.07 MiB/s, fertig.
Löse Unterschiede auf: 100% (6676/6676), fertig.
> ~/...
$ cd lazr.restful/
> ~/.../lazr.restful (main)
$ tox -epy27
GLOB sdist-make: .../lazr.restful/setup.py
py27 create: .../lazr.restful/.tox/py27
py27 installdeps: .[test,xml], zope.testrunner
py27 inst: .../lazr.restful/.tox/.tmp/package/1/lazr.restful-1.1.0.zip
py27 installed: DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.,configparser==4.0.2,contextlib2==0.6.0.post1,docutils==0.18,extras==1.0.0,fixtures==3.0.0,grokcore.component==3.2.0,importlib-metadata==2.1.2,lazr.batchnavigator==1.3.1,lazr.delegates==2.0.4,lazr.enum==1.2.1,lazr.lifecycle==1.2.1,lazr.restful @ file://.../lazr.restful/.tox/.tmp/package/1/lazr.restful-1.1.0.zip,lazr.uri==1.0.6,linecache2==1.0.0,lxml==4.6.4,martian==1.4,multipart==0.1.1,nose==1.3.7,pathlib2==2.3.6,pbr==5.7.0,python-gettext==4.0,python-mimeparse==1.6.0,pytz==2021.3,scandir==1.10.0,simplejson==3.17.6,six==1.16.0,testtools==2.4.0,traceback2==1.4.0,transaction==3.0.1,unittest2==1.1.0,van.testing==3.0.0,wsgi-intercept==1.9.2,zipp==1.2.0,zope.browser==2.3,zope.cachedescriptors==4.3.1,zope.component==5.0.1,zope.configuration==4.4.0,zope.contenttype==4.5.0,zope.datetime==4.3.0,zope.deprecation==4.4.0,zope.event==4.5.0,zope.exceptions==4.4,zope.hookable==5.1.0,zope.i18n==4.8.0,zope.i18nmessageid==5.0.1,zope.interface==5.4.0,zope.lifecycleevent==4.3,zope.location==4.2,zope.pagetemplate==4.6.0,zope.processlifetime==2.3.0,zope.proxy==4.5.0,zope.publisher==6.0.2,zope.schema==6.2.0,zope.security==5.1.1,zope.tal==4.5,zope.tales==5.1,zope.testing==4.9,zope.testrunner==5.3.0,zope.traversing==4.4.1
py27 run-test-pre: PYTHONHASHSEED='2488382268'
py27 run-test: commands[0] | zope-testrunner --test-path src --tests-pattern '^tests'
Running zope.testrunner.layer.UnitTests tests:
  Set up zope.testrunner.layer.UnitTests in 0.000 seconds.
  Ran 163 tests with 0 failures, 0 errors and 0 skipped in 2.185 seconds.
Running lazr.restful.example.base.tests.test_integration.WSGILayer tests:
  Tear down zope.testrunner.layer.UnitTests in 0.000 seconds.
  Set up lazr.restful.example.base.tests.test_integration.FunctionalLayer in 0.045 seconds.
  Set up lazr.restful.example.base.tests.test_integration.WSGILayer in 0.000 seconds.
  Ran 10 tests with 0 failures, 0 errors and 0 skipped in 1.571 seconds.
Running lazr.restful.example.base_extended.tests.test_integration.WSGILayer tests:
  Tear down lazr.restful.example.base.tests.test_integration.WSGILayer ... not supported
  Running in a subprocess.
  Set up lazr.restful.example.base_extended.tests.test_integration.FunctionalLayer in 0.081 seconds.
  Set up lazr.restful.example.base_extended.tests.test_integration.WSGILayer in 0.000 seconds.
  Ran 1 tests with 0 failures, 0 errors and 0 skipped in 0.009 seconds.
  Tear down lazr.restful.example.base_extended.tests.test_integration.WSGILayer ... not supported
  Tear down lazr.restful.example.base_extended.tests.test_integration.FunctionalLayer ... not supported
Running lazr.restful.example.multiversion.tests.test_integration.WSGILayer tests:
  Running in a subprocess.
  Set up lazr.restful.example.multiversion.tests.test_integration.FunctionalLayer in 0.067 seconds.
  Set up lazr.restful.example.multiversion.tests.test_integration.WSGILayer in 0.000 seconds.
  Ran 3 tests with 0 failures, 0 errors and 0 skipped in 0.182 seconds.
  Tear down lazr.restful.example.multiversion.tests.test_integration.WSGILayer in 0.000 seconds.
  Tear down lazr.restful.example.multiversion.tests.test_integration.FunctionalLayer in 0.000 seconds.
Running lazr.restful.example.wsgi.tests.test_integration.WSGILayer tests:
  Running in a subprocess.
  Set up lazr.restful.example.wsgi.tests.test_integration.FunctionalLayer in 0.059 seconds.
  Set up lazr.restful.example.wsgi.tests.test_integration.WSGILayer in 0.000 seconds.
  Ran 1 tests with 0 failures, 0 errors and 0 skipped in 0.008 seconds.
  Tear down lazr.restful.example.wsgi.tests.test_integration.WSGILayer in 0.000 seconds.
  Tear down lazr.restful.example.wsgi.tests.test_integration.FunctionalLayer in 0.000 seconds.
Running lazr.restful.tests.test_error.FunctionalLayer tests:
  Running in a subprocess.
  Set up lazr.restful.tests.test_error.FunctionalLayer in 0.082 seconds.
  Ran 15 tests with 0 failures, 0 errors and 0 skipped in 0.003 seconds.
  Tear down lazr.restful.tests.test_error.FunctionalLayer ... not supported
Running lazr.restful.tests.test_etag.FunctionalLayer tests:
  Running in a subprocess.
  Set up lazr.restful.tests.test_etag.FunctionalLayer in 0.079 seconds.
  Ran 5 tests with 0 failures, 0 errors and 0 skipped in 0.001 seconds.
  Tear down lazr.restful.tests.test_etag.FunctionalLayer ... not supported
Tearing down left over layers:
  Tear down lazr.restful.example.base.tests.test_integration.FunctionalLayer ... not supported
Total: 198 tests, 0 failures, 0 errors and 0 skipped in 8.018 seconds.
___________________________________ summary ____________________________________
  py27: commands succeeded
  congratulations :)
> ~/.../lazr.restful (main)
```

My machine is MacOS 11.6.1 on Intel architecture.

Could it be that you grabbed a wheel named `zope.proxy-4.5.0-py2.py3-none-any.whl`.
I removed it from PyPI because it cannot work. I am not sure how/why it was uploaded.

**Comment by cjwatson** [comment]
Hmm:

```
$ find ~/.cache/pip -name zope.proxy-4.5.0\*
/home/cjwatson/.cache/pip/wheels/6c/00/3f/060d3a6048a045cf45656aa2c5f75d4003973e09de2bd0276a/zope.proxy-4.5.0-cp35-cp35m-linux_x86_64.whl
/home/cjwatson/.cache/pip/wheels/47/87/1f/69d62e36963f1d20a1a7aa9381ae334b1868f0cb867da718ab/zope.proxy-4.5.0-cp27-cp27mu-linux_x86_64.whl
```

I deleted both of those and now things work, even though it's resulted in the same cached paths.  So I guess either `pip` downloaded the faulty wheel you mention and called it something else, or I somehow ended up with a corrupted wheel on disk; but in any case this seems solved, so thanks for your hint.
